name: ci

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: symlink gfortran (macOS)
        if: runner.os == 'macos'
        run: |
          ln -s /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
          gfortran --version
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose
      - run: cargo test --verbose
